### PR TITLE
Develop 1.9.18

### PR DESCRIPTION
**Pull request by gdevenyi**

### CODE REVIEW

**Comment by gdevenyi** [comment]
All these docker environments build, but I've run out of space on my home workstation to do the builds. Need to do some cleaning. Might be more changes coming.

**Comment by gdevenyi** [comment]
Current state of build scripts
- fedora rawhide is broken due to the docker base image being out-of-rate relative to the mass rebuild recently done (can't build image)
- TEST_BEAST fails everywhere
- centos8 minc-toolkit-v1 failing with ``./minc_wrapper: line 5: /home/nistmni/src/build/minc-toolkit/mni_autoreg/minctracc/param2xfm: Permission denied``, investigating
- debian_9_x64_v2, centos_6_x32_v2 and min_debian_8_x64_v2
failing with ``/home/nistmni/src/minc-toolkit-v2/libminc/libsrc/netcdf_convenience.c:573 (from miopen): Unable to open file '/home/nistmni/src/build/minc-toolkit-v2/mni_autoreg/Testing/ellipse0.mnc'`` considering the min/non-min version is something failing I think this may be a race condition or somesuch, investigating.

**Comment by gdevenyi** [comment]
I've got the following complete packages, still under the conditions above:
```
beast-library-1.1.0-20121212.deb
beast-library-1.1.0-20121212.rpm
bic-mni-models-0.1.1-20120421.deb
bic-mni-models-0.1.1-20120421.rpm
minc-toolkit-1.0.09-20170529-CentOS_6.10-i686.rpm
minc-toolkit-1.0.09-20170529-CentOS_6.10-x86_64.rpm
minc-toolkit-1.0.09-20170529-CentOS_8.2.2004-x86_64.rpm
minc-toolkit-1.0.09-20170529-Debian_8.11-x86_64.deb
minc-toolkit-1.0.09-20170529-Fedora_31-x86_64.rpm
minc-toolkit-1.0.09-20170529-Fedora_32-x86_64.rpm
minc-toolkit-1.0.09-20170529-Ubuntu_16.04-i686.deb
minc-toolkit-1.0.09-20170529-Ubuntu_16.04-x86_64.deb
minc-toolkit-1.0.09-20170529-Ubuntu_18.04-x86_64.deb
minc-toolkit-1.0.09-20170529-Ubuntu_20.04-x86_64.deb
minc-toolkit-1.9.18-20200813-CentOS_6.10-i686.rpm
minc-toolkit-1.9.18-20200813-CentOS_6.10-x86_64.rpm
minc-toolkit-1.9.18-20200813-CentOS_7.8.2003-x86_64.rpm
minc-toolkit-1.9.18-20200813-CentOS_8.2.2004-x86_64.rpm
minc-toolkit-1.9.18-20200813-Debian_8.11-x86_64.deb
minc-toolkit-1.9.18-20200813-Debian_9.12-x86_64.deb
minc-toolkit-1.9.18-20200813-Debian_10-x86_64.deb
minc-toolkit-1.9.18-20200813-Fedora_31-x86_64.rpm
minc-toolkit-1.9.18-20200813-Fedora_32-x86_64.rpm
minc-toolkit-1.9.18-20200813-Ubuntu_16.04-i686.deb
minc-toolkit-1.9.18-20200813-Ubuntu_16.04-x86_64.deb
minc-toolkit-1.9.18-20200813-Ubuntu_20.04-x86_64.deb
minc-toolkit-testsuite-0.1.3-20131212.deb
minc-toolkit-testsuite-0.1.3-20131212.rpm
```

Ok to upload?

**Comment by vfonov** [comment]
yes, go ahead

**Pull request merged**
