### PR TITLE
Improving Build Scripts

### PR DESCRIPTION
**Pull request by gdevenyi**
Thanks for the merge, I wasn't quite done my steps though :)

- [x] Making a bit simpler to add other platforms
- [x] Adding more platforms
- [x] update cmake
- [x] use official 32bit docker images
- [x] enable ccache across builds
- [x] enable download cache
- [x] prevent extra cups and X11 installs in build env
- [x] remove end-of-life distros

### CODE REVIEW

**Comment by gdevenyi** [comment]
After fixing and adjusting and updating, the following builds fail:

- minc-build_centos_6_x32_v2.log -- OpenBLAS build fail, binutils too old https://github.com/xianyi/OpenBLAS/issues/1841
devtoolset-3 seems to be broken and not downloadable

- minc-build_debian_9_x64_v1.log -- ITKv3 too old, VXL compiler error "Dunno about this GCC"

- minc-build_fedora_28_x64_v1.log -- ITKv3 too old, VXL compiler error "Dunno about this GCC"
- minc-build_fedora_28_x64_v2.log -- https://github.com/BIC-MNI/minc-toolkit-v2/issues/74
- minc-build_fedora_29_x64_v1.log -- ITKv3 too old, VXL compiler error "Dunno about this GCC"
- minc-build_fedora_29_x64_v2.log -- https://github.com/BIC-MNI/minc-toolkit-v2/issues/74
- minc-build_ubuntu_14.04_x32_v1.log -- OOOM RETEST
- minc-build_ubuntu_14.04_x32_v2.log -- OpenBLAS build fail, binutils too old https://github.com/xianyi/OpenBLAS/issues/1841
- minc-build_ubuntu_16.04_x32_v2.log -- OpenBLAS build fail, 32bit problem?
- minc-build_ubuntu_18.04_x64_v1.log -- ITKv3 too old, VXL compiler error "Dunno about this GCC"
- minc-build_ubuntu_18.10_x64_v1.log -- ITKv3 too old, VXL compiler error "Dunno about this GCC"
- minc-build_ubuntu_18.10_x64_v2.log -- https://github.com/BIC-MNI/minc-toolkit-v2/issues/74
- minc_min-build_centos_6_x32_v2.log -- OpenBLAS build fail, binutils too old https://github.com/xianyi/OpenBLAS/issues/1841
devtoolset-3 seems to be broken and not downloadable

- minc_min-build_fedora_28_x64_v2.log -- https://github.com/BIC-MNI/minc-toolkit-v2/issues/74
- minc_min-build_fedora_29_x64_v2.log -- https://github.com/BIC-MNI/minc-toolkit-v2/issues/74
- minc_min-build_ubuntu_14.04_x32_v2.log -- OpenBLAS build fail, binutils too old https://github.com/xianyi/OpenBLAS/issues/1841
devtoolset-3 seems to be broken and not downloadable
- minc_min-build_ubuntu_16.04_x32_v2.log -- OpenBLAS build fail 32 bit problem?
- minc_min-build_ubuntu_18.10_x64_v2.log -- https://github.com/BIC-MNI/minc-toolkit-v2/issues/74

**Comment by gdevenyi** [comment]
Looks like I could get devtoolset-6 for centos6...

**Comment by gdevenyi** [comment]
Currently testing devtools-6 builds

**Comment by gdevenyi** [comment]
Addressing "Dunno about GCC" with https://github.com/BIC-MNI/minc-toolkit/pull/53 and https://github.com/BIC-MNI/minc-toolkit/pull/54

**Comment by gdevenyi** [comment]
devtools-6 works for centos, but only available for x64 :(

**Comment by gdevenyi** [comment]
OpenBlas 32bit status: 
https://github.com/xianyi/OpenBLAS/issues/2056
https://github.com/xianyi/OpenBLAS/issues/2057

**Comment by gdevenyi** [comment]
Remaining bugs:
- https://github.com/xianyi/OpenBLAS/issues/2056 -- I will create a patch
- https://github.com/BIC-MNI/minc-toolkit/issues/40 -- can patch or copy cmake config, waiting feedback
- https://github.com/BIC-MNI/minc-toolkit-v2/issues/74 -- not sure how to fix, git drift issues
- devtools-6 issues with packaging -- investigating
- ubuntu 14.04 32bit -- virtual memory exhaustion on compile, not sure there's a solution for that, might be 32bit limits

**Comment by gdevenyi** [comment]
Still failing builds after
https://github.com/BIC-MNI/minc-toolkit-v2/pull/76
https://github.com/BIC-MNI/minc-toolkit-v2/pull/75 
https://github.com/BIC-MNI/minc-toolkit/pull/55
- minc-build_centos_6_x32_v2.log -- linking problems between beast and OpenMP
- minc-build_centos_6_x64_v1.log -- devtools-6 + stripping, see https://stackoverflow.com/questions/48706962/unresolvable-r-x86-64-none-relocation
- minc-build_ubuntu_14.04_x32_v1.log -- Virtual memory exhausted
- minc-build_ubuntu_14.04_x32_v2.log -- Virtual memory exhausted
- minc_min-build_centos_6_x32_v2.log -- linking problems with best and OpenMP as above
- minc_min-build_ubuntu_14.04_x32_v2.log -- Virtual memory exhausted

**Comment by vfonov** [comment]
I would say that 32 bit issues are not that important to fix, if debian 32 bit works and centos7 that would be enough.

**Comment by gdevenyi** [comment]
Based on my reading "virtual memory exhausted" might be a symptom from the host kernel rather than the underlying docker build, so you may have success (or other failures?) with the ubuntu system.

**Comment by gdevenyi** [comment]
Successful packages:
```
packages/beast-library-1.1.0-20121212.deb                         packages/minc-toolkit-1.0.09-20170529-Ubuntu_18.04-x86_64.deb     packages/minc-toolkit-testsuite-0.1.3-20131212.deb
packages/beast-library-1.1.0-20121212.rpm                         packages/minc-toolkit-1.0.09-20170529-Ubuntu_18.10-x86_64.deb     packages/minc-toolkit-testsuite-0.1.3-20131212.rpm
packages/bic-mni-models-0.1.1-20120421.deb                        packages/minc-toolkit-1.9.17-20181127-CentOS_6.10-x86_64.rpm      packages/min/minc-toolkit-1.9.17-20181127-CentOS_6.10-x86_64.rpm
packages/bic-mni-models-0.1.1-20120421.rpm                        packages/minc-toolkit-1.9.17-20181127-CentOS_7.6.1810-x86_64.rpm  packages/min/minc-toolkit-1.9.17-20181127-CentOS_7.6.1810-x86_64.rpm
packages/minc-toolkit-1.0.09-20170529-CentOS_6.10-x86_64.rpm      packages/minc-toolkit-1.9.17-20181127-Debian_8.11-x86_64.deb      packages/min/minc-toolkit-1.9.17-20181127-Debian_8.11-x86_64.deb
packages/minc-toolkit-1.0.09-20170529-CentOS_7.6.1810-x86_64.rpm  packages/minc-toolkit-1.9.17-20181127-Debian_9.8-x86_64.deb       packages/min/minc-toolkit-1.9.17-20181127-Debian_9.8-x86_64.deb
packages/minc-toolkit-1.0.09-20170529-Debian_8.11-x86_64.deb      packages/minc-toolkit-1.9.17-20181127-Fedora_28-x86_64.rpm        packages/min/minc-toolkit-1.9.17-20181127-Fedora_28-x86_64.rpm
packages/minc-toolkit-1.0.09-20170529-Debian_9.8-x86_64.deb       packages/minc-toolkit-1.9.17-20181127-Fedora_29-x86_64.rpm        packages/min/minc-toolkit-1.9.17-20181127-Fedora_29-x86_64.rpm
packages/minc-toolkit-1.0.09-20170529-Fedora_28-x86_64.rpm        packages/minc-toolkit-1.9.17-20181127-Ubuntu_14.04-x86_64.deb     packages/min/minc-toolkit-1.9.17-20181127-Ubuntu_14.04-x86_64.deb
packages/minc-toolkit-1.0.09-20170529-Fedora_29-x86_64.rpm        packages/minc-toolkit-1.9.17-20181127-Ubuntu_16.04-x86_64.deb     packages/min/minc-toolkit-1.9.17-20181127-Ubuntu_16.04-x86_64.deb
packages/minc-toolkit-1.0.09-20170529-Ubuntu_14.04-x86_64.deb     packages/minc-toolkit-1.9.17-20181127-Ubuntu_18.04-x86_64.deb     packages/min/minc-toolkit-1.9.17-20181127-Ubuntu_18.04-x86_64.deb
packages/minc-toolkit-1.0.09-20170529-Ubuntu_16.04-x86_64.deb     packages/minc-toolkit-1.9.17-20181127-Ubuntu_18.10-x86_64.deb     packages/min/minc-toolkit-1.9.17-20181127-Ubuntu_18.10-x86_64.deb

```

**Comment by vfonov** [comment]
if you can upload them on the BIC system, I can put them into http://packages.bic.mni.mcgill.ca/minc-toolkit/

**Comment by vfonov** [comment]
does this include https://github.com/BIC-MNI/EZminc/issues/11 ?

**Comment by vfonov** [comment]
also, maybe we should update the release data ( 20181127 -> 20190313 ) ?

**Comment by gdevenyi** [comment]
I believe it does, but yeah we should update the release date and rebuild one more time. Happy to do so.

**Comment by gdevenyi** [comment]
It would be good if those last few PRs were merged 
https://github.com/BIC-MNI/minc-toolkit-v2/pull/76
https://github.com/BIC-MNI/minc-toolkit-v2/pull/75

so that I build against official tree rather than my gabriel-develop where I merged my PRs

**Comment by gdevenyi** [comment]
Great. Everything is building again.

Give me a BIC path and I'll rsync them in when they're done.

**Comment by vfonov** [comment]
/scratch/scratch1/minc-toolkit

**Comment by gdevenyi** [comment]
packages/ directory upload complete.

**Comment by vfonov** [comment]
is it still transferring ?

**Comment by gdevenyi** [comment]
packages/ has this build
packages2/ has the build from #8 

Both are complete.

**Pull request merged**
